modLoader = "javafml"
loaderVersion = "[48,)"
issueTrackerURL = "https://github.com/Terrails/colorful-hearts"
license = "MIT"

[[mods]]
modId = "colorfulhearts"
version = "${version}"

displayName = "Colorful Hearts"
authors = "Terrails"
description = ''' A simple renderer for colored hearts '''

logoFile = "icon.png"
displayTest = "IGNORE_ALL_VERSION" # ignore everything since its a client only mod

[[dependencies.colorfulhearts]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.colorfulhearts]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "CLIENT"
